# Generated by Django 4.2.4 on 2023-08-21 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addressdetail',
            name='address_line1',
            field=models.CharField(max_length=325),
        ),
        migrations.AlterField(
            model_name='addressdetail',
            name='address_line2',
            field=models.CharField(max_length=325),
        ),
        migrations.AlterField(
            model_name='addressdetail',
            name='address_nick_name',
            field=models.CharField(max_length=325),
        ),
        migrations.AlterField(
            model_name='addressdetail',
            name='city',
            field=models.CharField(max_length=325),
        ),
        migrations.AlterField(
            model_name='addressdetail',
            name='country',
            field=models.CharField(max_length=325),
        ),
        migrations.AlterField(
            model_name='addressdetail',
            name='country_code',
            field=models.CharField(default=None, help_text='do not add + extension', max_length=35, null=True),
        ),
        migrations.AlterField(
            model_name='addressdetail',
            name='mobile_number',
            field=models.CharField(default=None, help_text='do not add country code', max_length=310, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='addressdetail',
            name='postal_code',
            field=models.CharField(max_length=325),
        ),
        migrations.AlterField(
            model_name='addressdetail',
            name='receivers_name',
            field=models.CharField(max_length=325),
        ),
        migrations.AlterField(
            model_name='currency',
            name='code',
            field=models.CharField(max_length=35, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='currency',
            name='name',
            field=models.CharField(max_length=315),
        ),
        migrations.AlterField(
            model_name='module',
            name='module_name',
            field=models.CharField(max_length=320),
        ),
        migrations.AlterField(
            model_name='product',
            name='dimension',
            field=models.CharField(help_text='The dimensions of the product in the format: Length*Width*Height.', max_length=320),
        ),
        migrations.AlterField(
            model_name='product',
            name='size',
            field=models.CharField(help_text='The size or measurement information of the product.', max_length=350),
        ),
        migrations.AlterField(
            model_name='productcategory',
            name='name',
            field=models.CharField(max_length=315),
        ),
        migrations.AlterField(
            model_name='subscriptiondetail',
            name='name',
            field=models.CharField(max_length=325),
        ),
        migrations.AlterField(
            model_name='user',
            name='country_code',
            field=models.CharField(default=None, help_text='do not add + extension', max_length=35, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='mobile_number',
            field=models.CharField(default=None, help_text='do not add country code', max_length=310, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(max_length=325),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(default=None, help_text='landline number', max_length=310, null=True),
        ),
        migrations.AlterField(
            model_name='websiteinfo',
            name='host_name',
            field=models.CharField(max_length=325, unique=True),
        ),
        migrations.AlterField(
            model_name='websiteinfo',
            name='website_name',
            field=models.CharField(max_length=325, unique=True),
        ),
    ]
